// Generated by gencpp from file race/drive_values.msg
// DO NOT EDIT!


#ifndef RACE_MESSAGE_DRIVE_VALUES_H
#define RACE_MESSAGE_DRIVE_VALUES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace race
{
template <class ContainerAllocator>
struct drive_values_
{
  typedef drive_values_<ContainerAllocator> Type;

  drive_values_()
    : throttle(0)
    , steering(0)  {
    }
  drive_values_(const ContainerAllocator& _alloc)
    : throttle(0)
    , steering(0)  {
  (void)_alloc;
    }



   typedef int16_t _throttle_type;
  _throttle_type throttle;

   typedef int16_t _steering_type;
  _steering_type steering;





  typedef boost::shared_ptr< ::race::drive_values_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::race::drive_values_<ContainerAllocator> const> ConstPtr;

}; // struct drive_values_

typedef ::race::drive_values_<std::allocator<void> > drive_values;

typedef boost::shared_ptr< ::race::drive_values > drive_valuesPtr;
typedef boost::shared_ptr< ::race::drive_values const> drive_valuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::race::drive_values_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::race::drive_values_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace race

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'race': ['/home/jaeshin/ISCC_2019/src/race/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::race::drive_values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::race::drive_values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::race::drive_values_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::race::drive_values_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::race::drive_values_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::race::drive_values_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::race::drive_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0194e179a126494f7021e4f23090fd6b";
  }

  static const char* value(const ::race::drive_values_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0194e179a126494fULL;
  static const uint64_t static_value2 = 0x7021e4f23090fd6bULL;
};

template<class ContainerAllocator>
struct DataType< ::race::drive_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "race/drive_values";
  }

  static const char* value(const ::race::drive_values_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::race::drive_values_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 throttle\n\
int16 steering\n\
";
  }

  static const char* value(const ::race::drive_values_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::race::drive_values_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drive_values_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::race::drive_values_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::race::drive_values_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.throttle);
    s << indent << "steering: ";
    Printer<int16_t>::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACE_MESSAGE_DRIVE_VALUES_H
